//Dashboard Actions
export const SWITCH_TO_ADD = "SWITCH_TO_ADD";
export const SWITCH_TO_UPDATE = "SWITCH_TO_UPDATE";
export const SWITCH_TO_REMOVE = "SWITCH_TO_REMOVE";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED";
export const UPDATE_A_PRODUCT = "UPDATE_A_PRODUCT";
export const UPDATE_A_PRODUCT_FAILED = "UPDATE_A_PRODUCT_FAILED";
export const REMOVE_A_PRODUCT = "REMOVE_A_PRODUCT";
export const REMOVE_A_PRODUCT_FAILED = "REMOVE_A_PRODUCT_FAILED";
export const FIND_A_PRODUCT = "FIND_A_PRODUCT";
export const FIND_A_PRODUCT_FAILED = "FIND_A_PRODUCT_FAILED";

//HomePage Actions
export const GET_NEWEST_PRODUCT = "GET_NEWEST_PRODUCT";
export const GET_NEWEST_PRODUCT_FAILED = "GET_NEWEST_PRODUCT_FAILED";

//Shop Actions
