//Dashboard Actions
export const SWITCH_TO_ADD = "SWITCH_TO_ADD"
export const SWITCH_TO_UPDATE = "SWITCH_TO_UPDATE"
export const SWITCH_TO_REMOVE = "SWITCH_TO_REMOVE"
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED"
export const UPDATE_A_PRODUCT = "UPDATE_A_PRODUCT"
export const UPDATE_A_PRODUCT_FAILED = "UPDATE_A_PRODUCT_FAILED"
export const REMOVE_A_PRODUCT = "REMOVE_A_PRODUCT"
export const REMOVE_A_PRODUCT_FAILED = "REMOVE_A_PRODUCT_FAILED"
export const FIND_A_PRODUCT = "FIND_A_PRODUCT"
export const FIND_A_PRODUCT_FAILED = "FIND_A_PRODUCT_FAILED"

//HomePage Actions
export const GET_NEWEST_PRODUCT = "GET_NEWEST_PRODUCT"
export const GET_NEWEST_PRODUCT_FAILED = "GET_NEWEST_PRODUCT_FAILED"
export const GET_THE_MOST_EXPENSIVE_PRODUCT = "GET_THE_MOST_EXPENSIVE_PRODUCT "
export const GET_THE_MOST_EXPENSIVE_PRODUCT_FAILED = "GET_THE_MOST_EXPENSIVE_PRODUCT_FAILED "

//Shop Actions
export const GET_ALL_SHOP_PRODUCT = "GET_ALL_SHOP_PRODUCT"
export const GET_ALL_SHOP_PRODUCT_FAILED = "GET_ALL_SHOP_PRODUCT_FAILED"
export const GET_SHIRT_SHOP_PRODUCT = "GET_SHIRT_SHOP_PRODUCT"
export const GET_SHIRT_SHOP_PRODUCT_FAILED = "GET_SHIRT_SHOP_PRODUCT_FAILED"
export const GET_TROUSER_SHOP_PRODUCT = "GET_TROUSER_SHOP_PRODUCT"
export const GET_TROUSER_SHOP_PRODUCT_FAILED = "GET_TROUSER_SHOP_PRODUCT_FAILED"
export const GET_DRESS_SHOP_PRODUCT = "GET_DRESS_SHOP_PRODUCT"
export const GET_DRESS_SHOP_PRODUCT_FAILED = "GET_DRESS_SHOP_PRODUCT_FAILED"
export const GET_COSTUME_SHOP_PRODUCT = "GET_COSTUME_SHOP_PRODUCT"
export const GET_COSTUME_SHOP_PRODUCT_FAILED = "GET_COSTUME_SHOP_PRODUCT_FAILED"
export const GET_ACCESSORY_SHOP_PRODUCT = "GET_ACCESSORY_SHOP_PRODUCT"
export const GET_ACCESSORY_SHOP_PRODUCT_FAILED = "GET_ACCESSORY_SHOP_PRODUCT_FAILED"
export const ACTIVED_PAGE = "ACTIVED_PAGE"
export const ACTIVED_CATEGORY = "ACTIVED_CATEGORY"

//Modal Actions
export const ACTIVE_MODAL = "ACTIVE_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const GET_PRODUCT_CONTENT = "GET_PRODUCT_CONTENT"

//Auth Actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"